//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.27 at 06:34:31 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.blck_rbbit.com/gbspringlessonschapter1/products", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.blck_rbbit.gbspringlessonschapter1.soap.products;
