server:
  port: 8701

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
            allowedHeaders: "*"
      routes:
        - id: core-service
          uri: http://localhost:8702/
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1
            - PrefixPath=/web-market-core
            - JwtAuthFilter
#        - id: cart-service
#          uri: http://localhost:8704/
#          predicates:
#            - Path=/cart/**
#          filters:
#            - StripPrefix=1
#            - PrefixPath=/market-cart
#            - JwtAuthFilter
        - id: auth-service
          uri: http://localhost:8703/
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/web-market-auth
            - JwtAuthFilter
jwt:
  secret: h4f8093h4f983yhrt9834hr0934hf0hf493g493gf438rh438th34g34g
  lifetime: 360000000

#logging:
#  level:
#    reactor:
#      netty: TRACE
#    org:
#      springframework:
#        cloud:
#          gateway: TRACE
