server:
  port: 8705
  servlet:
    context-path: /market-recommendation
spring:
  redis:
    timeout: 30000
integrations:
  core-service:
    url: http://localhost:8701/core
  cart-service:
    url: http://localhost:8701/cart